RUH-166 Microsite User Statistics Report
raccoongang/edx-platform pull request #2293
Opened 2021-01-26 17:45 UTC by UvgenGen

[RUH-166](https://youtrack.raccoongang.com/issue/RUH-166) Microsite User Statistics Report
- add a button for Microsite Reports (on Course -> Instructor -> Data Download)

2021-01-26 19:14 UTC, OPersian approved these changes

2021-01-26 19:26 UTC, GlugovGrGlib commented on lms/templates/instructor/instructor_dashboard_2/data_download.html
> +    <p><a href="${ section_data['get_microsite_reports_url'] }"><input type="button" name="microsite-reports" value="${_("Download site users report")}""></a></p>
There is a mess with the double quotes, use single quotes if possible

2021-01-26 19:26 UTC, GlugovGrGlib requested changes
Please look at the quotes, something isn't right

2021-01-27 10:53 UTC, GlugovGrGlib approved these changes

2021-01-27 10:54 UTC, merged