feat: [AXM-334] Allow easily adding Firebase credentials in Tutor
raccoongang/edx-platform pull request #2572
Opened 2024-06-10 15:37 UTC by KyryloKireiev

## Description

Allow easily adding Firebase credentials in tutor

So, to setup `FIREBASE_CREDENTIALS` we have to do two things:

1. Mount firebase_credentials.json to `lms` container;
2. Setup path to `firebase_credentials.json` in Tutor Plugin.

Detail instruction, how we can setup `FIREBASE_CREDENTIALS`:

1. Create file with FIREBASE_CREDENTIALS. For example firebase_credentials.json
2. Mount created file to LMS container:
`tutor mounts add lms:<path_to_file>/firebase_credentials.json:/openedx/<path_to_file_in_lms_container>/firebase_credentials.json`
`tutor config save` - docker-compose.yml file will be regenerated. And firebase_credentials.json file will be added to lms volume.
`tutor dev restart lms`
3. Now firebase_credentials.json is inside lms container. We can use path to this file for setup FIREBASE_CREDENTIALS_PATH constant.
We can setup FIREBASE_CREDENTIALS_PATH in tutor plugin. There is tutor plugin example:

```
from tutor import hooks

hooks.Filters.ENV_PATCHES.add_item(
    (
        "lms-env",

"""
FCM_APP_NAME: "fcm-edx-platform"
ACE_ENABLED_CHANNELS: 
  - "django_email"
  - "push_notification"
FIREBASE_CREDENTIALS_PATH: "/openedx/<path_to_file_in_lms_container>/firebase_credentials.json"
"""
    )
)
```

## YouTrack

https://youtrack.raccoongang.com/issue/AXM-334

2024-06-11 09:21 UTC, NiedielnitsevIvan requested changes

2024-06-11 09:21 UTC, NiedielnitsevIvan commented on openedx/core/djangoapps/ace_common/settings/common.py
> +    if used_firebase_credentials:
```suggestion
    settings.FIREBASE_APP = setup_firebase_app(settings.FIREBASE_CREDENTIALS_PATH or settings.FIREBASE_CREDENTIALS, settings.FCM_APP_NAME)
```

2024-06-11 09:21 UTC, NiedielnitsevIvan commented on openedx/core/djangoapps/ace_common/settings/production.py
> +        used_firebase_credentials = settings.FIREBASE_CREDENTIALS
Here the same

2024-06-11 09:35 UTC, KyryloKireiev commented on openedx/core/djangoapps/ace_common/settings/production.py
> +        used_firebase_credentials = settings.FIREBASE_CREDENTIALS
fixed

2024-06-12 17:27 UTC, NiedielnitsevIvan approved these changes

2024-06-14 06:25 UTC, merged